[project]
name = "dioxus-app"
revision = "1.0"

[profiles.default]
FLY_API_TOKEN = { description = "fly.io API token used by the deploy scripts" }

[profiles.development]
# deploying is optional during development
FLY_API_TOKEN = { required = false }
