[package]
name = "mobile"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
ui = { workspace = true }

[features]
default = []
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "ui/server"]
